/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChooseIcon: typeof import('./src/components/ChooseIcon.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    CustomTableColumn: typeof import('./src/components/CustomTableColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
